### ISSUE TITLE
Need to find a way to reduce memory requirements

### ISSUE THREAD

**Issue by quanah** [Symas/LogAnalyzer#6]
I attempted to analyze a 1.9GB logfile.  After 2 hours, the process was killed for consuming all available memory (40GB).

**Comment by quanah** [comment]
Note: The 1.9GB logfile was also only of sync data, no stats log data.  So there should really be nothing the script was tracking, and yet it consumed the 40GB of memory.  So we need to examine what we're doing...

**Comment by jtrupp** [comment]
Emmanuel, this needs your manipulation. Thanks!

**Comment by elecharny** [comment]
Quanah, can you mail me a few tens of lines so that I can debug the
analyzer to see where it eats the memory ?


Le 23/06/2017 à 15:57, Quanah Gibson-Mount a écrit :
> Note: The 1.9GB logfile was also only of sync data, no stats log data.  So there should really be nothing the script was tracking, and yet it consumed the 40GB of memory.  So we need to examine what we're doing...
>

-- 
Emmanuel Lecharny

Symas.com
directory.apache.org

**Comment by mistotebe** [comment]
My knee-jerk reaction:
Switching things into a few classes/generators, not saving all the strings and switch the long if-else statements into a dictionary lookup might be a first step to make it tractable

**Comment by quanah** [comment]
Just as an interesting comparison, parsing an 842MB log file:
```
quanah@ub16:~/git/symas/LogAnalyzer$ time ./symasLog.py  ~/customers/synacor/synaq/ldap02_zimbra.log
('Processing file : ', '/home/quanah/customers/synacor/synaq/ldap02_zimbra.log')
...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................Done, reading  7226240 lines


==========================================
== LDAP server restart #    0          ==
==========================================
Total Log Lines Analyzed: 7226240

----------- Access Log Output ------------

Start of Logs:     2017-06-08 03:35:01
End of Logs:       2017-06-08 13:25:44

Processed Log Time: 35443 seconds (9:50:43)

----------- Global statistics ------------
Total Connections:               14684
 - LDAPI Connections:         ***TODO***
Peak Concurrent Connections:  ***TODO***
Total Operations:                78909
Total Results:                   13503
Total Returned entries:         767649
Overall Performance:          2.23 operations/sec, 21.66 entries/sec

--------------- Operations ---------------
Binds:                           13503 (0.38/sec) (0.92/session)
    Simple:                      13503 (0.38/sec) (0.92/session)
Searches:                        65406 (1.85/sec) (4.45/session)

Number of Opened sessions :    14684
Number of Closed sessions :    14684
Number of Zombie sessions :       13


-------------- Errors found --------------

------------- Warnings found -------------
Not indexed attributes :


------- Miscellaneous informations -------
Average searches per connection :     4.45
Number of returned entries:   767649
Average entries per search :    11.74
Number of entries returned, grouped :    13503
Average number of searches per second when some searches are done :   4.014
---------------- Restarts ----------------

real    22m31.694s
user    20m54.736s
sys     1m36.812s
```

**Comment by quanah** [comment]
Compared to ldap-stats.pl:

```
time ./ldap-stats.pl ~/customers/synacor/synaq/ldap02_zimbra.log


Report Generated on Fri Jun 23 15:08:08 2017
--------------------------------------------
Processed "/home/quanah/customers/synacor/synaq/ldap02_zimbra.log":  Jun  8 03:35:01 - Jun  8 13:25:44


Operation totals
----------------
Total operations              : 61809
Total connections             : 14684
Total authentication failures : 0
Total binds                   : 13498
Total unbinds                 : 13503
Total searches                : 34808
Total compares                : 0
Total modifications           : 0
Total modrdns                 : 0
Total additions               : 0
Total deletions               : 0
Unindexed attribute requests  : 0
Operations per connection     : 4.21


Hostname         Connect Failed    Bind  Unbind   Search   Cmp   Add   Mod ModRDN  Del
--------------- -------- ------ ------- ------- -------- ----- ----- ----- ------ ----
10.1.5.101           315      0     315     315      619     0     0     0      0    0
10.1.5.102          3074      0    3074    3074     3380     0     0     0      0    0
10.1.5.140          2977      0    2977    2977     3183     0     0     0      0    0
10.1.5.143          2977      0    2977    2977     3182     0     0     0      0    0
10.1.5.149          2979      0    2979    2979     3186     0     0     0      0    0
10.1.5.195          1181      0       0       0        0     0     0     0      0    0
LOCAL-SOCKET        1181      0    1176    1181    21258     0     0     0      0    0


Hour of Day    Connect Failed    Bind  Unbind   Search   Cmp   Add   Mod ModRDN  Del
------------- -------- ------ ------- ------- -------- ----- ----- ----- ------ ----
03:00 - 03:59      618      0     569     569     1470     0     0     0      0    0
04:00 - 04:59     1490      0    1369    1370     3531     0     0     0      0    0
05:00 - 05:59     1487      0    1367    1367     3527     0     0     0      0    0
06:00 - 06:59     1486      0    1366    1366     3525     0     0     0      0    0
07:00 - 07:59     1485      0    1365    1365     3525     0     0     0      0    0
08:00 - 08:59     1487      0    1367    1367     3528     0     0     0      0    0
09:00 - 09:59     1490      0    1369    1370     3535     0     0     0      0    0
10:00 - 10:59     1492      0    1371    1372     3539     0     0     0      0    0
11:00 - 11:59     1484      0    1364    1364     3524     0     0     0      0    0
12:00 - 12:59     1486      0    1364    1366     3526     0     0     0      0    0
13:00 - 13:59      679      0     627     627     1578     0     0     0      0    0


Day of Month   Connect Failed    Bind  Unbind   Search   Cmp   Add   Mod ModRDN  Del
------------- -------- ------ ------- ------- -------- ----- ----- ----- ------ ----
  8              14684      0   13498   13503    34808     0     0     0      0    0


 Month         Connect Failed    Bind  Unbind   Search   Cmp   Add   Mod ModRDN  Del
------------- -------- ------ ------- ------- -------- ----- ----- ----- ------ ----
  Jun            14684      0   13498   13503    34808     0     0     0      0    0


# Searches    Search base
----------    -----------------------------------------------------------
  16954       cn=servers,cn=zimbra
  16589       RootDSE
  8204        cn=config,cn=zimbra
  2362        cn=operations,cn=monitor
  1228        cn=config
  1181        cn=read,cn=waiters,cn=monitor
  1181        cn=abandon,cn=operations,cn=monitor
  1181        cn=unbind,cn=operations,cn=monitor
  1181        cn=bind,cn=operations,cn=monitor
  1181        cn=modify,cn=operations,cn=monitor
  1181        cn=entries,cn=statistics,cn=monitor
  1181        cn=total,cn=connections,cn=monitor
  1181        cn=compare,cn=operations,cn=monitor
  1181        cn=modrdn,cn=operations,cn=monitor
  1181        cn=bytes,cn=statistics,cn=monitor
  1181        cn=delete,cn=operations,cn=monitor
  1181        cn=write,cn=waiters,cn=monitor
  1181        cn=add,cn=operations,cn=monitor
  1181        cn=referrals,cn=statistics,cn=monitor
  1181        cn=search,cn=operations,cn=monitor
  1181        cn=extended,cn=operations,cn=monitor
  586         cn=ldap01-dc01.cm.synaq.com,cn=servers,cn=zimbra
  586         cn=ldap02-dc01.cm.synaq.com,cn=servers,cn=zimbra
  1           dc=ascendisdirect,dc=com


# Uses        Filter
----------    -----------------------------------------------------------
  47223       (objectClass=*)
  2772        (cn=ldap06-dc01.cm.synaq.com)
  2772        (cn=ldap08-dc01.cm.synaq.com)
  2771        (cn=ldap10-dc01.cm.synaq.com)
  2768        (cn=ldap02-dc01.cm.synaq.com)
  2344        (objectClass=zimbraServer)
  1228        (olcServerID=*)
  1172        (&(objectClass=zimbraServer)(zimbraServiceEnabled=service))
  1172        (&(objectClass=zimbraServer)(zimbraServiceEnabled=memcached))
  1172        (&(objectClass=zimbraServer)(zimbraServiceEnabled=mailbox))
  11          (cn=ldap01-dc01.cm.synaq.com)
  1           (&(|(zimbraAccountStatus=active)(objectClass=zimbraDistributionList))(!(objectClass=zimbraCalendarResource))(!(zimbraHideInGal=TRUE)))


# Uses        Attributes explicitly requested in search string
----------    -------------------------------------------------
  15361       1.1
  12991       monitoropcompleted
  11094       zimbraserviceenabled
  7086        monitorcounter
  1228        contextcsn
  1228        olcserverid
  1181        monitoropinitiated
  1           co company description givenname gn initials l objectclass ou physicaldeliveryofficename postalcode sn st street streetaddress telephonenumber title whenchanged modifytimestamp whencreated createtimestamp zimbraid zimbramaildeliveryaddress zimbramailalias mail facsimiletelephonenumber fax hometelephonenumber homephone mobiletelephonenumber mobile pagertelephonenumber pager displayname cn zimbracalrestype msexchresourcesearchproperties zimbramailforwardingaddress zimbracalresbuilding zimbracalrescapacity msexchresourcecapacity zimbracalresfloor zimbracalressite zimbracalrescontactemail msexchresourcesearchproperties zimbraphoneticcompany ms-ds-phonetic-company-name zimbraphoneticfirstname ms-ds-phonetic-first-name zimbraphoneticlastname ms-ds-phonetic-last-name zimbracalreslocationdisplayname usercertificate usersmimecertificate zimbradistributionlistsubscriptionpolicy zimbradistributionlistunsubscriptionpolicy zimbranotes zimbraaccountcalendarusertype zimbracalrestype zimbracalreslocationdisplayname zimbracalrescapacity zimbracalrescontactemail


# Binds       Bind DN
----------    --------------------------------------------------------------
  12275       uid=zimbra,cn=admins,cn=zimbra
  1228        cn=config



real    0m22.749s
user    0m22.328s
sys     0m0.416s
```

**Comment by jtrupp** [comment]
Please note the difference in time it took to run both scripts.

**Comment by elecharny** [comment]
There is definitively some profiling to do on the python script...

**Comment by elecharny** [comment]
Regarding memory consumption : 
- we keep a track of each search filter for each session. That eats a lot of space
- regarding performances : I have a fix that speed up the process by an order of magnitude.

**Comment by elecharny** [comment]
FTR, I ran the latest version on a 1.6Gb file, with 16M lines of logs. It took only 422 seconds to process, and ate around 9GB.

**Comment by elecharny** [comment]
last profile session tells that sorting the result and computing results using floating numbers is what cost the most (with the decimal.py functions being called milions of time with a heavy cost as a result). Switching to integer computation should save a lot of time.

**Comment by elecharny** [comment]
The use of Decimal has been removed, for a 20% improvement n speed. The analyzer can now process more than 50 000 lines per second, processing 16 millions on line takes 340 seconds, compared to the 600 s it took in a previous version for which the date have been already optimized. That is roughly a 20x improvement.

It will be herd to find some big improvements now...

**Comment by quanah** [comment]
Excellent, I'll play with this now on some log files. :)

**Comment by platipusica** [comment]
Hi there, 

looks like I can't parse 550M log file. 

Also, where do I find ldap-stats.pl?

Thanks

**Comment by elecharny** [comment]
Weird. I was able to parse a 1.6Gb log file (see upper in the comments)

What kind of error do you get ? Is it possible to send us the log file ?

**Comment by platipusica** [comment]
Hi
thanks for your reply. The log is 15 MB zipped, where can I send it? The output is:
.
.
('Processed :', 24, '%')
Traceback (most recent call last):
  File "symasLog.py", line 1108, in <module>
    processLog( openLdapLogs, args, counters, True )
  File "symasLog.py", line 978, in processLog
    processLine( counters, line, pos, counters.nbProcessedLines, connectionId, reqDate, args.traceMode )
  File "symasLog.py", line 142, in processLine
    processSearchRequest( counters, session, line, pos, length, totalSeconds )
  File "/home/dbabic/Downloads/LogAnalyzer-master/operations/Search.py", line 261, in processSearchRequest
    search = processSearchFirstLine( line, pos, session, totalSeconds )
  File "/home/dbabic/Downloads/LogAnalyzer-master/operations/Search.py", line 63, in processSearchFirstLine
    result = getDn( line, pos)
  File "/home/dbabic/Downloads/LogAnalyzer-master/utils/symasLogUtils.py", line 165, in getDn
    while ( ( line[pos] != '"' ) & ( pos < length ) ) :
IndexError: string index out of range

**Comment by elecharny** [comment]
can you try to send it to elecharny@symas.com ?

**Comment by platipusica** [comment]
Will do, thx.

**Comment by elecharny** [comment]
There is an obvious bug in this function : we try to access a char at a give position *before* checking that the position is valid.

**Comment by elecharny** [comment]
It's even worse : we use '&' instead of 'and', which means the whole expression is computed, no matter what. Using a 'and' and moving the ( pos < length ) test at first position solve the issue.

**Comment by elecharny** [comment]
I just commited a fix

**Comment by ljudva** [comment]
Hi, 
still happening, I've sent you the logs (I'm the same guy).

**Comment by platipusica** [comment]
Whow, thank for providing a fix, it is now processing 550MB quite fast:

`---------------- Restarts ----------------
Restart #                    0         1
Lines             :    5077513   1503982
Line/second       :     181.37    189.25
Duration          :  7:46:35   2:12:27  
Connections       :      39023     11297
Operations        :     220440     65468
Entries           :     501240    137080
Operations/second :       7.87      8.24
Entries/second    :      17.90     17.25
`

**Comment by ljudva** [comment]
Whow, thanks for providing a fix, it is now processing 550MB quite fast!

Excellent work, good on you guys!

```
==========================================
== LDAP server restart #    1          ==
==========================================
Total Log Lines Analyzed: 1503982

----------- Access Log Output ------------

Start of Logs:     2018-02-07 11:49:17
End of Logs:       2018-02-07 14:01:44

Processed Log Time: 7947 seconds (2:12:27)

----------- Global statistics ------------
Restarts:                           1
Total Connections:               11297
 - StartTLS Connections:             9
 - LDAPI Connections:         ***TODO***
Peak Concurrent Connections:  ***TODO***
Total Operations:                65468
Total Results:                   10134
Total Returned entries:         137080
Overall Performance:          8.24 operations/sec, 17.25 entries/sec

--------------- Operations ---------------
Binds:                           10134 (1.28/sec) (0.90/session)
    Simple:                      10134 (1.28/sec) (0.90/session)
Modifications:                       4 (0.00/sec) (0.00/session)
Mod RDNs:                            2 (0.00/sec) (0.00/session)
Searches:                        44204 (5.56/sec) (3.91/session)
Unbinds:                         11124 (1.40/sec) (0.98/session)

Number of Opened sessions:    11297
Number of Closed sessions:    11275
Number of Zombie sessions:       22


-------------- Errors found --------------
    4 SIZE_LIMIT_EXCEEDED errors found
  598 NO_SUCH_OBJECT errors found
    2 INVALID_DN_SYNTAX errors found

------------- Warnings found -------------
Not indexed attributes: 


------- Miscellaneous informations -------
Average searches per connection:     3.91
Number of returned entries:   137080
Average entries per search:     3.10
Number of entries returned, grouped:    10134
Average number of searches per second when some searches are done:   9.867
---------------- Restarts ----------------

real	0m30.944s
user	0m29.168s
sys	0m1.270s
```

**Comment by shirfan** [comment]
I think memory issue is still there. Processing 1.4G of log file consumed all 8gb of system RAM and sysmasLog.py paused.  

(python2.7) [root@support zimbra]# time python2.7 /home/irfan/LogAnalyzer/symasLog.py zimbra.log --zombieSessions --restarts --ips --sessions --spreadModDN
('Processing file: ', 'zimbra.log')
('Processed:', 1, '%')
('Processed:', 2, '%')
('Processed:', 3, '%')
('Processed:', 4, '%')
('Processed:', 5, '%')
('Processed:', 6, '%')
('Processed:', 7, '%')
('Processed:', 8, '%')
('Processed:', 9, '%')
('Processed:', 10, '%')
('Processed:', 11, '%')
('Processed:', 12, '%')
('Processed:', 13, '%')
('Processed:', 14, '%')
('Processed:', 15, '%')
('Processed:', 16, '%')
('Processed:', 17, '%')
('Processed:', 18, '%')
('Processed:', 19, '%')
('Processed:', 20, '%')
('Processed:', 21, '%')
('Processed:', 22, '%')
('Processed:', 23, '%')
('Processed:', 24, '%')
('Processed:', 25, '%')
('Processed:', 26, '%')
('Processed:', 27, '%')
('Processed:', 28, '%')
('Processed:', 29, '%')
('Processed:', 30, '%')
('Processed:', 31, '%')
('Processed:', 32, '%')
('Processed:', 33, '%')
('Processed:', 34, '%')
('Processed:', 35, '%')
('Processed:', 36, '%')
('Processed:', 37, '%')
('Processed:', 38, '%')
('Processed:', 39, '%')
('Processed:', 40, '%')
('Processed:', 41, '%')
('Processed:', 42, '%')
('Processed:', 43, '%')
('Processed:', 44, '%')
('Processed:', 45, '%')
('Processed:', 46, '%')
('Processed:', 47, '%')
('Processed:', 48, '%')
('Processed:', 49, '%')
('Processed:', 50, '%')
('Processed:', 51, '%')
('Processed:', 52, '%')
('Processed:', 53, '%')
('Processed:', 54, '%')
('Processed:', 55, '%')
('Processed:', 56, '%')
('Processed:', 57, '%')
('Processed:', 58, '%')
('Processed:', 59, '%')
('Processed:', 60, '%')
('Processed:', 61, '%')
('Processed:', 62, '%')
('Processed:', 63, '%')
('Processed:', 64, '%')
('Processed:', 65, '%')
('Processed:', 66, '%')
('Processed:', 67, '%')
('Processed:', 68, '%')
('Processed:', 69, '%')
('Processed:', 70, '%')
('Processed:', 71, '%')
('Processed:', 72, '%')
('Processed:', 73, '%')
('Processed:', 74, '%')
('Processed:', 75, '%')
('Processed:', 76, '%')
('Processed:', 77, '%')
('Processed:', 78, '%')
('Processed:', 79, '%')
('Processed:', 80, '%')
('Processed:', 81, '%')
('Processed:', 82, '%')
('Processed:', 83, '%')
('Processed:', 84, '%')
('Processed:', 85, '%')
('Processed:', 86, '%')
('Processed:', 87, '%')
('Processed:', 88, '%')
('Processed:', 89, '%')
('Processed:', 90, '%')
('Processed:', 91, '%')
('Processed:', 92, '%')
('Processed:', 93, '%')
('Processed:', 94, '%')
('Processed:', 95, '%')

('Processed:', 96, '%')
('Processed:', 97, '%')
('Processed:', 98, '%')
('Processed:', 99, '%')
('Processed:', 100, '%')
Done, reading 11874448 lines
Delta:  3864255ms


==========================================
== LDAP server restart #    0          ==
==========================================
Total Log Lines Analyzed: 11874448

----------- Access Log Output ------------

Start of Logs:     2018-02-13 03:24:02
End of Logs:       2018-02-13 14:47:10

Processed Log Time: 40988 seconds (11:23:08)

----------- Global statistics ------------
Total Connections:              521258
 - StartTLS Connections:           264
 - LDAPI Connections:         ***TODO***
Peak Concurrent Connections:  ***TODO***
Total Operations:              3410568
Total Results:                  593628
Overall Performance:          83.21 operations/sec, 0.00 entries/sec

--------------- Operations ---------------
Adds:                              665 (0.02/sec) (0.00/session)
Binds:                          519891 (12.68/sec) (1.00/session)
    Simple:                     519891 (12.68/sec) (1.00/session)
Deletes:                          1970 (0.05/sec) (0.00/session)
Extendeds:                         559 (0.01/sec) (0.00/session)
Modifications:                   70538 (1.72/sec) (0.14/session)
Mod RDNs:                            4 (0.00/sec) (0.00/session)
Searches:                      2816941 (68.73/sec) (5.40/session)

Number of Opened sessions:   521258
Number of Closed sessions:   521163
Number of Zombie sessions:     1245

------------- Load spreading -------------
ModDNs per 20 minutes:
03:20        0:
03:40        0:
04:00        0:
04:20        0:
04:40        0:
05:00        0:
05:20        0:
05:40        0:
06:00        0:
06:20        0:
06:40        0:
07:00        0:
07:20        0:
07:40        0:
08:00        0:
08:20        0:
08:40        0:
09:00        1: ########################################
09:20        0:
09:40        0:
10:00        0:
10:20        0:
10:40        0:
11:00        0:
11:20        1: ########################################
11:40        0:
12:00        0:
12:20        0:
12:40        0:
13:00        0:
13:20        0:
13:40        0:
14:00        0:
14:20        2: ################################################################################
14:40        0:
15:00        0:


-------------- Errors found --------------
   38 NO_SUCH_ATTRIBUTE errors found
    3 ATTRIBUTE_OR_VALUE_EXISTS errors found
    1 NO_SUCH_OBJECT error found
    3 INVALID_DN_SYNTAX errors found
   42 ENTRY_ALREADY_EXISTS errors found

------------- Warnings found -------------
Not indexed attributes:

---------- 10 Busiest sessions -----------

('>---- sessionId    : ', '138650316', ', duration :', 111.0, 's, IP: ', '10.1.11.117')
    nbOperations   :   32486
    nbBind         :       1
       nbTls       :       1
       nbSimple    :       1
    nbExtOp        :       1
    nbSearch       :   32484


('>---- sessionId    : ', '138776894', ', duration :', 126.0, 's, IP: ', '10.1.11.123')
    nbOperations   :   29058
    nbBind         :       1
       nbSimple    :       1
    nbSearch       :   29057


('>---- sessionId    : ', '138936629', ', duration :', 136.0, 's, IP: ', '10.1.11.123')
    nbOperations   :   27921
    nbBind         :       1
       nbSimple    :       1
    nbSearch       :   27920


('>---- sessionId    : ', '138650640', ', duration :', 81.0, 's, IP: ', '10.1.11.117')
    nbOperations   :   22782
    nbBind         :       1
       nbTls       :       1
       nbSimple    :       1
    nbExtOp        :       1
    nbSearch       :   22780


('>---- sessionId    : ', '138776154', ', duration :', 748.0, 's, IP: ', '10.1.11.117')
    nbOperations   :    5398
    nbBind         :       1
       nbTls       :       1
       nbSimple    :       1
    nbExtOp        :       1
    nbSearch       :    5396


('>---- sessionId    : ', '138706399', ', duration :', 436.0, 's, IP: ', '10.1.11.117')
    nbOperations   :    4987
    nbBind         :       1
       nbTls       :       1
       nbSimple    :       1
    nbExtOp        :       1
    nbSearch       :    4985


('>---- sessionId    : ', '139065075', ', duration :', 264.0, 's, IP: ', '10.1.11.117')
    nbOperations   :    4846
    nbBind         :       1
       nbTls       :       1
       nbSimple    :       1
    nbExtOp        :       1
    nbSearch       :    4844


('>---- sessionId    : ', '139098186', ', duration :', 563.0, 's, IP: ', '10.1.11.117')
    nbOperations   :    4278
    nbBind         :       1
       nbTls       :       1
       nbSimple    :       1
    nbExtOp        :       1
    nbSearch       :    4276

('>---- sessionId    : ', '138908583', ', duration :', 231.0, 's, IP: ', '10.1.11.117')
    nbOperations   :    3874
    nbBind         :       1
       nbTls       :       1
       nbSimple    :       1
    nbExtOp        :       1
    nbSearch       :    3872

('>---- sessionId    : ', '139000359', ', duration :', 550.0, 's, IP: ', '10.1.11.117')
    nbOperations   :    3448
    nbBind         :       1
       nbTls       :       1
       nbSimple    :       1
    nbExtOp        :       1
    nbSearch       :    3446

------- Miscellaneous informations -------
Average searches per connection:     5.40
Average entries per search:     0.00
Number of entries returned, grouped:   593628
Average number of searches per second when some searches are done:  68.928

------ 10 longest zombie sessions -------

('>---- sessionId    : ', '130678751', ', duration: ', 0, ' seconds')
    nbDelete       :       6
    nbModify       :     145
    nbSearch       :    1606

('>---- sessionId    : ', '130678757', ', duration: ', 0, ' seconds')
    nbAdd          :       1
    nbDelete       :       7
    nbModify       :     118
    nbSearch       :    1583

('>---- sessionId    : ', '130394064', ', duration: ', 0, ' seconds')
    nbSearch       :    1365

('>---- sessionId    : ', '130685844', ', duration: ', 0, ' seconds')
    nbSearch       :    1366

('>---- sessionId    : ', '130685845', ', duration: ', 0, ' seconds')
    nbSearch       :    1407

('>---- sessionId    : ', '130682823', ', duration: ', 0, ' seconds')
    nbSearch       :    1365

('>---- sessionId    : ', '132124902', ', duration: ', 0, ' seconds')
    nbDelete       :       1
    nbExtOp        :       2
    nbModify       :     116
    nbSearch       :    1589

('>---- sessionId    : ', '130713037', ', duration: ', 0, ' seconds')
    nbDelete       :       4
    nbModify       :     164
    nbSearch       :    1638

('>---- sessionId    : ', '139079868', ', duration: ', 0, ' seconds')

('>---- sessionId    : ', '130687013', ', duration: ', 0, ' seconds')
    nbDelete       :       3
    nbModify       :     114
    nbSearch       :    1555

---------------- Restarts ----------------
Restart #                    0
Lines             :   11874448
Line/second       :     289.71
Duration          :  11:23:08
Connections       :     521258
Operations        :    3410568
Entries           :          0
Operations/second :      83.21
Entries/second    :       0.00

**^C**

**real	83m50.174s**
user	11m23.987s
sys	1m32.031s

**Comment by elecharny** [comment]
Le 15/02/2018 à 17:13, shirfan a écrit :
> I think memory issue is still there. Processing 1.4G of log file consumed all 8gb of system RAM and sysmasLog.py paused.  

Actually, we don't try to 'manage' memory in any way.

We stoe each operation in memory, in order to be able to list the
longest/ore costly operations at the end.

We could do better, but that would require much more effort.

Now, that's an open source project, and we welcome any contribution :-)

**Comment by platipusica** [comment]
Agreed.

my 2.4G log on a VM 2CPU's, 8Gb ram:
```
--------------- Restarts ----------------
Restart #                    0         1         2         3
Lines             :    5077513  14609409  11442333    145609
Line/second       :     181.37    773.15    297.19    146.19
Duration          :  7:46:35   5:14:56   10:41:42  0:16:36  
Connections       :      39023     25093     44397       695
Operations        :     220440    148242    555996      6756
Entries           :     501240    302678    758702     14331
Operations/second :       7.87      7.85     14.44      6.78
Entries/second    :      17.90     16.02     19.71     14.39
```
```
free
              total        used        free      shared  buff/cache   available
Mem:        5973120     2367916      111160      687004     3494044     2609900
Swap:       2095100         524     2094576
free
              total        used        free      shared  buff/cache   available
Mem:        5973120     2486140      113432      686996     3373548     2491828
Swap:       2095100         524     2094576
free
              total        used        free      shared  buff/cache   available
Mem:        5973120     2506248      128708      686996     3338164     2472292
Swap:       2095100         524     2094576
 free
              total        used        free      shared  buff/cache   available
Mem:        5973120     2039972      608844      686996     3324304     2938800
Swap:       2095100         780     2094320
free
              total        used        free      shared  buff/cache   available
Mem:        5973120      802324     1834700      686996     3336096     4176492
```
